apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: jonesthomas/test-node-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
   
# service type NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nodejs-app
  namespace: default
spec:
  rules:
    - host: devops1.fsgarage.in
      http:
        paths:
          - backend:
              serviceName: nodejs-app
              servicePort: 3000
            path: /
