---
- hosts: all
  #become: true
  #vars:
  #  ansible_ssh_private_key_file: "/home/ubuntu/.ssh/id_rsa"
  tasks:
  - name: Stop and remove the exists container
    command: docker stop test-node-Container && docker rm test-node-Container
    ignore_error: true
    
  - name: Remove the old Image
    command: docker rmi jonesthomas/test-node-image:latest
    ignore_error: true
    
  - name: Pull docker image from docker hub
    command: docker pull jonesthomas/test-node-image:latest

  - name: Create container using the image
    command: docker run -d  --name test-node-Container -p 80:80 jonesthomas/test-node-image:latest
