---
- hosts: all
  ignore_errors: yes
  tasks:

  - block:
    - name: Stop the exists container
      command: docker stop test-node-Container
    - name: Remove the exists container
      command: docker rm test-node-Container
    - name: Remove the old Image
      command: docker rmi jonesthomas/test-node-image:latest

  - name: Pull docker image from docker hub
    command: docker pull jonesthomas/test-node-image:latest
  - name: Create container using the image
    command: docker run -d  --name test-node-Container -p 80:80 jonesthomas/test-node-image:latest
